FROM apache/airflow:3.2.1-python3.12

RUN pip install --no-cache-dir \
    apache-airflow-providers-standard==1.12.0 \
    apache-airflow-providers-apache-spark==6.0.0 \
    apache-airflow-providers-apache-kafka==1.13.0 \
    apache-airflow-providers-postgres==6.6.0 \
    apache-airflow-providers-amazon==9.6.0 \
    kafka-python>=2.0.2 \
    boto3 \
    pyarrow
